# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Spotify' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Spotify
  
  # SnapKit
  pod 'SnapKit', '~> 5.6.0'
  
  # Alamofire
  pod 'Alamofire'
  
  # KeychainAccess
  pod 'KeychainAccess'
  
  # RxSwift
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  
  # SDWebImage
  pod 'SDWebImage', '~> 5.0'

end
